# -*- coding: utf-8 -*-
"""fft_group1_csc821

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UF4fPnilWeD9ovl5PKFPVLuv2aU7t42
"""

#Implements the Fast Fourier Transform (Cooley-Tukey, radix-2, decimation-in-time)


import cmath #Provides mathematical functions for complex numbers
import math # Provides mathematical functions for real floating-point numbers.
import numpy as np #Adds support for large, multi-dimensional arrays
import matplotlib.pyplot as plt #used for plotting and visualising



# FFT ALGORITHM (Cooley-Tukey, radix-2, recursive)

def fft(x):

   # Compute the Discrete Fourier Transform of x using the recursive
   #radix-2 Cooley-Tukey Fast Fourier Transform algorithm.

    n = len(x)

    # Base case of the recursion
    if n == 1:
        return np.array(x, dtype=complex)

    if n % 2 != 0:
        raise ValueError("Length of input must be a power of 2 for this radix-2 FFT")

    # Divide: split into even- and odd-indexed elements
    even = fft(x[0::2])
    odd = fft(x[1::2])

    # Conquer: combine using twiddle factors e^(-2*pi*i*k/n)
    result = np.zeros(n, dtype=complex)
    for k in range(n // 2):
        twiddle = cmath.exp(-2j * math.pi * k / n) * odd[k]
        result[k] = even[k] + twiddle
        result[k + n // 2] = even[k] - twiddle

    return result


def next_power_of_two(n):
    #Return the smallest power of 2 that is >= n (used for zero-padding)
    return 1 if n == 0 else 2 ** (n - 1).bit_length()



# BUILD A TEST SIGNAL

def build_test_signal():

    #Create a synthetic signal made of two sine waves (50 Hz and 120 Hz)

    sample_rate = 800          # samples per second (Hz)
    duration = 1.0             # seconds
    n_samples = int(sample_rate * duration)
    n_samples = next_power_of_two(n_samples)  # radix-2 FFT needs power-of-2 length

    t = np.arange(n_samples) / sample_rate

    freq1, amp1 = 50, 1.0     # 50 Hz component
    freq2, amp2 = 120, 0.5    # 120 Hz component

    signal = (
        amp1 * np.sin(2 * np.pi * freq1 * t)
        + amp2 * np.sin(2 * np.pi * freq2 * t)
    )

    # small amount of random noise to make it realistic
    rng = np.random.default_rng(seed=42)
    signal += 0.2 * rng.standard_normal(n_samples)

    return t, signal, sample_rate



# RUN + PLOT

def main():
    t, signal, sample_rate = build_test_signal()
    n = len(signal)

    # --- Run our own FFT implementation ---
    spectrum = fft(signal)

    # Frequency axis: only the first half is meaningful for a real-valued
    # signal (the second half is a mirror image, per the Nyquist theorem).
    freqs = np.fft.fftfreq(n, d=1 / sample_rate)
    half = n // 2

    magnitude = np.abs(spectrum) / n  # normalise by number of samples

    # --- Sanity check against NumPy's built-in FFT ---
    numpy_spectrum = np.fft.fft(signal)
    max_diff = np.max(np.abs(spectrum - numpy_spectrum))
    print(f"Signal length (samples): {n}")
    print(f"Sample rate: {sample_rate} Hz")
    print(f"Max difference vs numpy.fft.fft: {max_diff:.2e}  (should be ~0)")

    # Report the strongest frequency peaks found
    peak_idx = np.argsort(magnitude[:half])[::-1][:2]
    print("Top detected frequencies:")
    for idx in sorted(peak_idx):
        print(f"  {freqs[idx]:6.1f} Hz  |  magnitude = {magnitude[idx]:.3f}")

    # --- Plot ---
    fig, axes = plt.subplots(2, 1, figsize=(10, 7))

    axes[0].plot(t, signal, color="steelblue", linewidth=0.9)
    axes[0].set_title("Original Signal (Time Domain)")
    axes[0].set_xlabel("Time (s)")
    axes[0].set_ylabel("Amplitude")
    axes[0].grid(alpha=0.3)

    axes[1].stem(freqs[:half], magnitude[:half], basefmt=" ")
    axes[1].set_title("Frequency Spectrum (FFT Result)")
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_ylabel("Magnitude")
    axes[1].set_xlim(0, sample_rate / 2)
    axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig("fft_group.png", dpi=150)
    print("\nPlot saved to fft_group.png")


if __name__ == "__main__":
    main()